In [14]:
import pandas as pd
pd.set_option('display.max_colwidth', -1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  


In [15]:
import numpy as np
import pandas as pd
from scipy.stats import itemfreq
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer


### Understanding word2vec

In [16]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [17]:
from gensim.models.keyedvectors import KeyedVectors
w2vec = KeyedVectors.load_word2vec_format("/gdrive/My Drive/Deep Learning AIML/Statistical NLP/Notebooks/gensim_glove.6B.50d.txt", binary=False)

In [18]:
a = w2vec.word_vec("prince")
b = w2vec.word_vec("man")
c = w2vec.word_vec("princess")
d = w2vec.word_vec("woman")
e = w2vec.word_vec("fantastic")
f = w2vec.word_vec("amazing")
g = w2vec.word_vec("great")
h = w2vec.word_vec("bad")

In [19]:
a

array([ 9.8846e-01,  1.4535e+00, -5.3081e-01,  1.0509e-01,  8.4058e-01,
        1.4018e-01,  6.6562e-02,  1.3341e+00, -7.5813e-01, -3.5223e-01,
        1.6588e-01,  1.0016e+00,  1.9623e-02, -6.6392e-01,  9.2825e-02,
        2.5132e-01, -1.6274e-01, -1.1954e-01, -5.0072e-01,  6.7374e-01,
        6.6886e-01, -3.8679e-02,  2.0223e-01, -1.5211e-01,  1.2169e-01,
       -1.8324e+00, -8.5664e-01, -6.2454e-01, -3.1896e-01,  6.0221e-01,
        1.4110e+00,  5.0157e-01, -1.1413e-01,  5.1808e-01,  8.4700e-01,
        1.7618e-01, -3.5265e-02,  5.6405e-01, -3.8524e-01,  6.0270e-01,
        3.4331e-01,  1.1836e+00, -3.7197e-01, -1.1069e+00,  1.2758e-04,
       -1.8202e-01, -1.3696e+00, -1.4970e+00,  4.0618e-01, -4.2445e-01],
      dtype=float32)

In [20]:
w2vec.wv.most_similar('king')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


[('prince', 0.8236179351806641),
 ('queen', 0.7839042544364929),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247181892395),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542160749435425),
 ('throne', 0.7539913654327393),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253096580505)]

In [21]:
w2vec.most_similar(positive=['king','prince'], negative=['princess'])

[('ruler', 0.7564873695373535),
 ('succeeded', 0.7022944092750549),
 ('brother', 0.7022433280944824),
 ('henry', 0.6932743191719055),
 ('edward', 0.6926167607307434),
 ('ali', 0.6923112273216248),
 ('sultan', 0.6916553378105164),
 ('charles', 0.686941921710968),
 ('nephew', 0.6842198967933655),
 ('uncle', 0.6790000796318054)]

In [22]:
d

array([-1.8153e-01,  6.4827e-01, -5.8210e-01, -4.9451e-01,  1.5415e+00,
        1.3450e+00, -4.3305e-01,  5.8059e-01,  3.5556e-01, -2.5184e-01,
        2.0254e-01, -7.1643e-01,  3.0610e-01,  5.6127e-01,  8.3928e-01,
       -3.8085e-01, -9.0875e-01,  4.3326e-01, -1.4436e-02,  2.3725e-01,
       -5.3799e-01,  1.7773e+00, -6.6433e-02,  6.9795e-01,  6.9291e-01,
       -2.6739e+00, -7.6805e-01,  3.3929e-01,  1.9695e-01, -3.5245e-01,
        2.2920e+00, -2.7411e-01, -3.0169e-01,  8.5286e-04,  1.6923e-01,
        9.1433e-02, -2.3610e-02,  3.6236e-02,  3.4488e-01, -8.3947e-01,
       -2.5174e-01,  4.2123e-01,  4.8616e-01,  2.2325e-02,  5.5760e-01,
       -8.5223e-01, -2.3073e-01, -1.3138e+00,  4.8764e-01, -1.0467e-01],
      dtype=float32)

In [26]:
from scipy.stats.stats import pearsonr
pearsonr(e,f)

(0.8790130399273265, 4.7052455461111284e-17)

In [27]:
from scipy.stats.stats import pearsonr
pearsonr(g,h)

(0.6451530228512765, 4.2449909683657265e-07)

### Finding sentence vectors from word vectors


In [28]:
title1 = "laws of physics"
title2 = "theory of relativity"
title3 = "battle of panipat"

#### Assignment: Find vector representation for each title by splitting the title into indivdiual words. Find vector for each word and average them. What's the pearson correlation between different titles?

In [29]:
w1 = w2vec.word_vec("laws")
w2 = w2vec.word_vec("of")
w3 = w2vec.word_vec("physics")
w4 = w2vec.word_vec("theory")
w5 = w2vec.word_vec("of")
w6 = w2vec.word_vec("relativity")
w7 = w2vec.word_vec("battle")
w8 = w2vec.word_vec("of")
w9 = w2vec.word_vec("panipat")

In [30]:
title1wv = (w1+w2+w3)/3
title2wv = (w4+w5+w6)/3
title3wv = (w7+w8+w9)/3

In [31]:
title1wv

array([-0.41165003,  0.32106668, -0.548472  , -0.14604734, -0.08014334,
        0.57921   ,  0.37322664, -0.91621333, -0.05222334,  0.10800999,
        0.34717265,  0.19584   , -0.19510369, -0.09276666,  0.13078   ,
        0.02793   ,  0.06941167,  0.11746033, -0.28263333, -0.18569799,
        0.6268566 , -0.00835667, -0.02554965, -0.31514   ,  0.05773   ,
       -1.7224334 , -0.505338  , -0.62672   , -0.25312   ,  0.14738333,
        2.6731665 , -0.52106   , -0.79387   , -1.3824034 ,  0.04651667,
       -0.14059454, -0.06331   ,  0.31441465,  0.33561668,  0.6332434 ,
       -0.31546   , -0.08330967,  0.656381  ,  0.799454  , -0.5040233 ,
        0.28109732,  0.25718665,  0.24763334,  0.06121065, -0.43976998],
      dtype=float32)

In [32]:
pearsonr(title1wv,title2wv)

(0.8310371748765593, 8.078782492695916e-14)

In [33]:
pearsonr(title2wv,title3wv)

(0.4834915892035435, 0.0003753148507448383)

### Finding similiar books

In [34]:
books_data = pd.read_csv('/gdrive/My Drive/Deep Learning AIML/Statistical NLP/Notebooks/books.csv',encoding="latin")

In [35]:
books_data.shape

(5700, 2)

In [36]:
books_data.columns

Index(['title', 'category'], dtype='object')

In [37]:
import re
books_data["title_clean"] = [re.sub("[^a-zA-Z ]","",x).lower() for x in books_data["title"]]

In [38]:
from tqdm import tqdm
title_vec = np.zeros((books_data.shape[0],50))
for i in tqdm(range(0,books_data.shape[0])):
    words = books_data["title_clean"].iloc[i].split(" ")
    words = [x.strip() for x in words]
    ind_word_vecs = [w2vec.word_vec(x) for x in words if x in w2vec.vocab]
    title_vec[i] = np.array(ind_word_vecs).mean(axis=0)

  0%|          | 0/5700 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: Mean of empty slice.
  import sys
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5700/5700 [00:00<00:00, 24449.25it/s]


In [39]:
title_vec = np.nan_to_num(title_vec)

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
cosine_sim_titles = cosine_similarity(title_vec)

In [42]:
cosine_sim_titles.shape

(5700, 5700)

In [43]:
# get books similiar to a given title..

title_id = 13
books_data['title'].iloc[title_id]

'Organ Transplantation (Health and Medical Issues Today)'

In [44]:
### Q: Find the titles with the highest degree of similarity (top 10)
top_n_idx = 10
top_n_sim_values = cosine_sim_titles[title_id, top_n_idx]
top_n_sim_values

0.7729226325263809

In [ ]:
# find top n with values > 0
top_n_idx = top_n_idx[top_n_sim_values > 0]

TypeError: ignored

In [ ]:
# Matching books
books_data['title'].iloc[top_n_idx]

"Almost Anorexic: Is My (or My Loved One's) Relationship with Food a Problem? (The Almost Effect)"

<b> Q: find the most similiar books corresponding to title id 34 - "Shadowrun: Third Edition (FPR25000)". 
What issues do you see with the results </b>

### Using TF IDF with word2vec

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer


In [ ]:
# initialize vectorizer
vect = TfidfVectorizer(ngram_range=(1,2),stop_words='english', max_features=5000)


In [ ]:
vect.fit(books_data['title_clean'])
title_matrix = vect.transform(books_data['title_clean'])

In [ ]:
title_matrix = title_matrix.toarray()

In [ ]:
title_matrix.shape

(5700, 5000)

In [ ]:
# get tf idf weights
idx = 34
features = np.where(title_matrix[idx,:] > 0)[0]

In [ ]:
feature_names = [vect.get_feature_names()[x] for x in features]
feature_names

['edition', 'shadowrun']

#### Find the tf-idf weights of the 2 words. Which word has a higher weightage?

In [ ]:
# feature weights
feature_weights = np.array([title_matrix[idx,x] for x in features])[:,np.newaxis]
feature_weights.shape

(2, 1)

In [ ]:
# multiplying tf idf weights with word2vec

word_vecs = np.array([w2vec.word_vec(x) if x in w2vec.vocab else np.zeros(50) for x in feature_names])

In [ ]:
word_vecs.shape

(2, 50)

In [ ]:
res = word_vecs*feature_weights

In [ ]:
res.shape[0]

2

In [ ]:
def get_weighted_vectors(idx):
    
    features = np.where(title_matrix[idx,:] > 0)[0]
    feature_names = [vect.get_feature_names()[x] for x in features]
    feature_weights = np.array([title_matrix[idx,x] for x in features])[:,np.newaxis]
    word_vecs = np.array([w2vec.word_vec(x) if x in w2vec.vocab else np.zeros(50) for x in feature_names])
    res = word_vecs*feature_weights
    return res.mean(axis=0)
    

In [ ]:
from tqdm import tqdm
title_vec_weighted = np.zeros((books_data.shape[0],50))
for i in tqdm(range(0,books_data.shape[0])):
    vec = get_weighted_vectors(i)
    
    if vec.shape[0] == 0:
        title_vec_weighted[i] = np.zeros(50)
    else:
        title_vec_weighted[i] = vec

  1%|          | 39/5700 [00:00<01:33, 60.50it/s]/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: Mean of empty slice.
  
100%|██████████| 5700/5700 [01:35<00:00, 59.47it/s]


In [ ]:
title_id=34
books_data['title'].iloc[title_id]

'Shadowrun: Third Edition (FPR25000)'

In [ ]:

cosine_sim_titles_weighted = cosine_similarity(title_vec_weighted)
top_n_idx = np.flip(np.argsort(cosine_sim_titles_weighted[title_id,]),axis=0)[0:10]
top_n_sim_values = cosine_sim_titles_weighted[title_id, top_n_idx]
top_n_sim_values

# find top n with values > 0
top_n_idx = top_n_idx[top_n_sim_values > 0]
# Matching books
books_data['title'].iloc[top_n_idx]

34      Shadowrun: Third Edition (FPR25000)                                                                                                                                                        
4879    Shadowrun 4th Edition                                                                                                                                                                      
2795    Shadowrun Unwired (Shadowrun (Catalyst Hardcover))                                                                                                                                         
4660    Rigger 2: A Shadowrun Sourcebook                                                                                                                                                           
3956    Minecraft Pocket Edition: The Minecraft Pocket Edition Essentials Handbook Guide to Minecraft (An Unofficial Minecraft Pocket Edition Handbook) ... edition, minecraft handbook, minecraft)
274     Sixth World 