In [2]:
import pandas as ps
import numpy as np

In [3]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [5]:
flowers = ps.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [8]:
football = [24 23 34 46 65 67]

SyntaxError: invalid syntax (<ipython-input-8-085dac5840a2>, line 1)

In [7]:
print (football)

[24, 235, 34, 456, 65, 67]


In [9]:
   data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = ps.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [10]:
score = [10, 15, 20, 25]

ps.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [11]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [13]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

demo_matrix[2,3]

39

In [14]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [15]:
demo_array=np.arange(0,10) 

In [16]:
demo_array

demo_array <3

demo_array[demo_array <6]

np.max(demo_array)

9

In [17]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
demo_array <3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [19]:
demo_array[demo_array <6]

array([0, 1, 2, 3, 4, 5])

In [20]:
np.max(demo_array)

9

In [25]:
s1 = ps.Series(['a', 'b'])
s2 = ps.Series(['c', 'd'])

In [26]:
s1

0    a
1    b
dtype: object

In [27]:
s2

0    c
1    d
dtype: object

In [29]:
ps.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [32]:
pd.concat([s1+ s2])

NameError: name 'pd' is not defined

In [33]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [34]:
football=[2,3,4]
np.array(football)

array([2, 3, 4])