In [78]:
#importing modules
import numpy as np 
import pandas as pd 

#loading datasets
data = pd.read_csv("D:\gli\dse\data\wisc_bc_data.csv")

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
id                   569 non-null int64
diagnosis            569 non-null object
radius_mean          569 non-null float64
texture_mean         569 non-null float64
perimeter_mean       569 non-null float64
area_mean            569 non-null float64
smoothness_mean      569 non-null float64
compactness_mean     569 non-null float64
concavity_mean       569 non-null float64
points_mean          569 non-null float64
symmetry_mean        569 non-null float64
dimension_mean       569 non-null float64
radius_se            569 non-null float64
texture_se           569 non-null float64
perimeter_se         569 non-null float64
area_se              569 non-null float64
smoothness_se        569 non-null float64
compactness_se       569 non-null float64
concavity_se         569 non-null float64
points_se            569 non-null float64
symmetry_se          569 non-null float64
dimension_se    

In [84]:
data.head(5)
data.diagnosis.value_counts()


0    357
1    212
Name: diagnosis, dtype: int64

In [85]:
#diagnosis variable is a responsible variable for the classification
#replacing M and B with 1 and 0 respectively
data.diagnosis=data.diagnosis.map({'M':1,'B':0})

In [86]:
#finished the dataset preprocessing
#splitting dataset into training one and testing one
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.3)

In [83]:
#making independent variables for training
train_X = train.iloc[:, 1:31]
#making responsible variables for training
train_y=train.diagnosis
#making independent variables for testing
test_X= test.iloc[:, 1:31]
#making responsible variables for testing
test_y =test.diagnosis#finding out the results


## Single testing strategy is not reliable

In [52]:

#1-1,DesicionTree

#importing module
from sklearn.tree import DecisionTreeClassifier
#making the instance
model= DecisionTreeClassifier(random_state=1234)
#learning
model.fit(train_X,train_y)
#Prediction
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9590643274853801
Confusion Metrix:
 [[107   3]
 [  4  57]]


In [67]:
# Creating a new test data
train, test = train_test_split(data, test_size = 0.3)

test_X= test.iloc[:, 1:31]

test_y =test.diagnosis
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9941520467836257
Confusion Metrix:
 [[111   1]
 [  0  59]]


In [68]:
# SVM

#importing module
from sklearn import svm
#making the instance
model = svm.SVC(random_state=123)
#learning
model.fit(train_X,train_y)
#Prediction
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9590643274853801
Confusion Metrix:
 [[111   7]
 [  0  53]]


In [69]:
# Creating a new test data
train, test = train_test_split(data, test_size = 0.3)

test_X= test.iloc[:, 1:31]

test_y =test.diagnosis
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9122807017543859
Confusion Metrix:
 [[106  12]
 [  3  50]]


In [70]:

#KNeighbors

#importing module
from sklearn.neighbors import KNeighborsClassifier
#making the instance
model = KNeighborsClassifier(n_jobs=-1)
#learning
model.fit(train_X,train_y)
#Prediction
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Matrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9239766081871345
Confusion Matrix:
 [[102   6]
 [  7  56]]


In [72]:
# Creating a new test data
train, test = train_test_split(data, test_size = 0.3)

test_X= test.iloc[:, 1:31]

test_y =test.diagnosis
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9649122807017544
Confusion Metrix:
 [[104   4]
 [  2  61]]


In [73]:
#Logistic Regression

#importing module
from sklearn.linear_model import LogisticRegression
#making the instance
model = LogisticRegression()
#learning
model.fit(train_X,train_y)
#Prediction
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Matrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9649122807017544
Confusion Matrix:
 [[103   3]
 [  3  62]]


d:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [74]:
# Creating a new test data
train, test = train_test_split(data, test_size = 0.3)

test_X= test.iloc[:, 1:31]

test_y =test.diagnosis
prediction=model.predict(test_X)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,test_y))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,test_y))

Accuracy: 0.9415204678362573
Confusion Metrix:
 [[102   8]
 [  2  59]]


# Single testing is not a reliable way of establishing model performance