In [ ]:
import numpy as np
import pandas as pd

In [ ]:
R = pd.read_csv('mousehunt-rewardmatrix.csv' , header = None)

In [ ]:
R

0  1  2  3  4  5  6  7  8    9
0 -1 -1 -1  0 -1 -1 -1 -1 -1   -1
1 -1 -1  0 -1 -1 -1 -1 -1 -1   -1
2 -1  0 -1 -1 -1  0 -1 -1 -1  100
3  0 -1 -1 -1  0 -1  0 -1 -1   -1
4 -1 -1 -1  0 -1  0 -1  0 -1   -1
5 -1 -1  0 -1  0 -1 -1 -1 -1   -1
6 -1 -1 -1  0 -1 -1 -1 -1 -1   -1
7 -1 -1 -1 -1  0 -1 -1 -1  0  100
8 -1 -1 -1 -1 -1 -1 -1  0 -1   -1
9 -1 -1  0 -1 -1 -1 -1  0 -1  100

In [ ]:
R = np.matrix(R)

In [ ]:
R

matrix([[ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,   0,  -1,  -1,  -1,   0,  -1,  -1,  -1, 100],
        [  0,  -1,  -1,  -1,   0,  -1,   0,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,   0,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,   0,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,   0, 100],
        [ -1,  -1,  -1,  -1,  -1,  -1,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,   0,  -1, 100]])

In [ ]:
Q = np.zeros ([10,10])

In [ ]:
Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Set gamma parameter

gamma = 0.7

# Initial  state for the mouse(Later, we will make this random)

initial_state = 2

In [ ]:
# Custom function that returns all avlb actions for the given state of the mouse

def avl_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row > -1)[1]
  return av_act

In [ ]:
available_actions = avl_actions(initial_state)

In [ ]:
available_actions

array([1, 5, 9])

In [ ]:
# Next , we will construct a fn which randomly chooses an action from the avlb actions

def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_actions_range,1))
  return next_action

In [ ]:
action = sample_next_action(available_actions)
action

9

In [ ]:
action

9

In [ ]:
# Update the Q Matrix according to the path selected using the Q learning formula


def update(current_state,action,gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[0]

  if max_index.shape[0] > 1:
    max_index = int(np.random.choice(max_index,1))

  else:
    max_index - int(max_index)

  max_value = Q[action,max_index]

  #Q-Learning Formula
  Q[current_state,action] = R[current_state,action] + gamma*max_value

In [ ]:
#Update the Q Matrix
update(initial_state,action,gamma)

In [ ]:
Q

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [ ]:
# Repeat the above steps using a for loop

for i in range(1000):
  current_state = np.random.choice(range(10))
  available_act = avl_actions(current_state)
  action = sample_next_action(available_act)
  update(current_state,action,gamma)

In [ ]:
(Q / np.max(Q)) * 100

array([[  0.        ,   0.        ,   0.        ,  34.29988029,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  69.9997557 ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,  48.99982899,   0.        ,   0.        ,
          0.        ,  48.99971744,   0.        ,   0.        ,
          0.        ,  99.999651  ],
       [ 24.00928489,   0.        ,   0.        ,   0.        ,
         48.99982899,   0.        ,  24.00967191,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,  34.29988029,
          0.        ,  48.99982899,   0.        ,  69.9997557 ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  69.9997557 ,   0.        ,
         48.99982899,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  

In [ ]:
# Test the Q Matrix using one scenario

# Goal_state = 9

#Current_state = 6

# Best Sequence of path starting from state 6 = 6, 3, 4, 7, 9

In [ ]:
current_state = 5
steps = [current_state]

while current_state != 9:
  next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]

  if next_step_index.shape[0] > 1:
    next_step_index = int(np.random.choice(next_step_index,1))

  else:
    next_step_index = int(next_step_index)

  steps.append(next_step_index)

  current_state = next_step_index



print("The selected path:")
print(steps)

The selected path:
[5, 2, 9]


[6]